name: Feature Request
description: Suggest a new feature or enhancement for Flowise
title: '[FEATURE] '
labels: ['enhancement']
assignees: []
body:
    - type: markdown
      attributes:
          value: |
              Thanks for suggesting a new feature! Please provide as much detail as possible to help us understand your request.

    - type: textarea
      id: feature-description
      attributes:
          label: Feature Description
          description: A clear and concise description of the feature you'd like to see in Flowise.
          placeholder: Describe what you want to be added or improved...
      validations:
          required: true

    - type: dropdown
      id: feature-category
      attributes:
          label: Feature Category
          description: What category does this feature belong to?
          options:
              - UI/UX Improvement
              - New Node/Component
              - Integration
              - Performance
              - Security
              - Documentation
              - API Enhancement
              - Workflow/Flow Management
              - Authentication/Authorization
              - Database/Storage
              - Deployment/DevOps
              - Other
      validations:
          required: true

    - type: textarea
      id: problem-statement
      attributes:
          label: Problem Statement
          description: What problem does this feature solve? What's the current pain point?
          placeholder: Describe the problem or limitation you're facing...
      validations:
          required: true

    - type: textarea
      id: proposed-solution
      attributes:
          label: Proposed Solution
          description: How would you like this feature to work? Be as specific as possible.
          placeholder: Describe your ideal solution in detail...
      validations:
          required: true

    - type: textarea
      id: use-cases
      attributes:
          label: Use Cases
          description: Provide specific examples of how this feature would be used.
          placeholder: |
              Example use cases:
              1. As a [user type], I want to [action] so that [benefit]
              2. When [scenario], I need [functionality] to [outcome]
      validations:
          required: true

    - type: dropdown
      id: user-type
      attributes:
          label: Primary User Type
          description: Who would primarily benefit from this feature?
          options:
              - End Users (Flow Creators)
              - Developers/Integrators
              - System Administrators
              - Enterprise Users
              - All Users
              - Other
      validations:
          required: true

    - type: dropdown
      id: priority
      attributes:
          label: Priority Level
          description: How important is this feature to you?
          options:
              - Low - Nice to have
              - Medium - Would improve workflow
              - High - Significantly impacts productivity
              - Critical - Blocking current work
      validations:
          required: true

    - type: textarea
      id: alternatives
      attributes:
          label: Alternatives Considered
          description: Have you considered any alternative solutions or workarounds?
          placeholder: Describe any workarounds you're currently using or other solutions you've considered...

    - type: textarea
      id: implementation-ideas
      attributes:
          label: Implementation Ideas
          description: Do you have any ideas on how this could be implemented? (Optional - for technical users)
          placeholder: Any technical suggestions, API changes, or implementation approaches...

    - type: textarea
      id: mockups-references
      attributes:
          label: Mockups or References
          description: Any mockups, screenshots, or references to similar features in other tools?
          placeholder: Upload images or provide links to examples...

    - type: checkboxes
      id: related-areas
      attributes:
          label: Related Areas (Select all that apply)
          description: Which parts of Flowise would this feature impact?
          options:
              - label: Canvas/Flow Editor
              - label: Node Library
              - label: Chat Interface
              - label: API
              - label: Database
              - label: Authentication
              - label: File Management
              - label: Analytics/Monitoring
              - label: Deployment
              - label: Documentation

    - type: textarea
      id: additional-context
      attributes:
          label: Additional Context
          description: Any other information, context, or examples that would help us understand this request.
          placeholder: Add any other relevant information...
